### ISSUE TITLE
ZNS - Open Details of a Transaction

### ISSUE THREAD

**Issue by migueltrevinom** [Open-Verifik/zelf-extension#5]
<img width="431" alt="Image" src="https://github.com/user-attachments/assets/8b0cb478-cd5a-4225-b835-00752c841bc4" />

## Description

This screen is required to have a static look with a dynamic functionality which is the check of confirmations when the transaction hasn't been completed yet.

So for this task we will get a transaction object from the list of transactions, we will check the status, and based on the status we will decide if we have to keep doing a query to retrieve the latest information or we just get the static information and the component is considered complete.

### TODO

- [ ] Design the static page with the information required to put there (might be different per network, we will start with ETH)

- [ ] Code the functions to retrieve an updated status and values from the transaction that was passed in the init function

**Comment by andresflondono** [comment]
This will be the view screen for the extension. 

<img width="899" alt="Image" src="https://github.com/user-attachments/assets/6eed0ef2-d43c-40bd-8c8b-29a41616d90d" />

**Comment by Casta1984** [comment]
- [x] It was verified that the designed static page correctly displays the information corresponding to the ETH network, meeting the established requirements. Likewise, it was confirmed that the implemented functions accurately and in real time retrieve the updated status and values of the transaction received in the initialization function.
